name: "Tests"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  tests:
    uses: "SciML/.github/.github/workflows/grouped-tests.yml@v1"
    secrets: "inherit"
